INSERT INTO Roles (`name`, `description`, createdat, updatedat) VALUES ('Adminitrator', 'Administrator role', NOW(), NOW());
INSERT INTO Roles (`name`, `description`, createdat, updatedat) VALUES ('Cliente', 'Cliente role', NOW(), NOW());
INSERT INTO Userstatuses (`name`, `description`, createdat, updatedat) VALUES ('Registrado', 'Status Registrado', NOW(), NOW());
INSERT INTO Userstatuses (`name`, `description`, createdat, updatedat) VALUES ('Activo', 'Status Activo', NOW(), NOW());
INSERT INTO States (`name`, createdat, updatedat) VALUES ('Guatemala', NOW(),NOW());
INSERT INTO Cities (`name`, stateid, createdat, updatedat) VALUES ('Guatemala', 1, NOW(),NOW());
INSERT INTO Cities (`name`, stateid, createdat, updatedat) VALUES ('San Jose Pinula', 1, NOW(),NOW());
INSERT INTO Shippingstatuscategories (`name`, `description`,  createdAt, updatedAt) VALUES ('Inicial', 'Inicial', NOW(), NOW());
INSERT INTO Shippingstatuses (`name`, `description`, categoryid, createdAt, updatedAt) VALUES ('Creado', 'Creado', 1, NOW(), NOW());
INSERT INTO Shippingstatuses (`name`, `description`, categoryid, createdAt, updatedAt) VALUES ('Aceptada', 'Aceptada', 1, NOW(), NOW());
INSERT INTO Shippingstatuses (`name`, `description`, categoryid, createdAt, updatedAt) VALUES ('En ruta', 'Recibida y en ruta', 1, NOW(), NOW());
INSERT INTO Shippingstatuses (`name`, `description`, categoryid, createdAt, updatedAt) VALUES ('Entregada', 'Entregada', 1, NOW(), NOW());
INSERT INTO Shippingstatuses (`name`, `description`, categoryid, createdAt, updatedAt) VALUES ('Cancelada', 'Cancelada', 1, NOW(), NOW());
INSERT INTO Shippingstatuses (`name`, `description`, categoryid, createdAt, updatedAt) VALUES ('Completada', 'Completada', 1, NOW(), NOW());
INSERT INTO Filetypes(`name`, `description`, createdAt, updatedAt) VALUES ('Usuario', 'Imagen de perfil de usuario', NOW(), NOW());
INSERT INTO Filetypes(`name`, `description`, createdAt, updatedAt) VALUES ('SAT', 'Imagen de carnet de SAT', NOW(), NOW());
INSERT INTO Filetypes(`name`, `description`, createdAt, updatedAt) VALUES ('Policiacos', 'Imagen de antecedentes policiacos', NOW(), NOW());
INSERT INTO Filetypes(`name`, `description`, createdAt, updatedAt) VALUES ('Penales', 'Imagen de antecedentes penales', NOW(), NOW());
INSERT INTO Filetypes(`name`, `description`, createdAt, updatedAt) VALUES ('Envio', 'Imagen del envio', NOW(), NOW());
INSERT INTO Filetypes (`name`, `description`, createdAt, updatedAt) VALUES ('Recepcion', 'Imagen de recepcion de envio', NOW(), NOW());
INSERT INTO Filetypes (`name`, `description`, createdAt, updatedAt)  VALUES ('Entrega', 'Imagen de entrega de envio', NOW(), NOW());
INSERT INTO Filestatuses (`name`, `description`, createdAt, updatedAt) VALUES ('Ingresado', 'Ingresado', NOW(), NOW());
INSERT INTO Filestatuses (`name`, `description`, createdAt, updatedAt) VALUES ('Verificado', 'Verificado', NOW(), NOW());
INSERT INTO Filestatuses (`name`, `description`, createdAt, updatedAt) VALUES ('Vencido', 'Vencido', NOW(), NOW());
